title: Karella's blog
email: karella@utia.cas.cz
description: >- # this means to ignore newlines until "baseurl:"
  Several notes and blogs to publish
domain: karellat.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://karellat.github.io  # the base hostname and protocol for your site, e.g. http://example.com
#baseurl: /karellat.github.io/
github_username:  karellat

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

head_scripts:
  - https://code.jquery.com/jquery-3.2.1.min.js
# - /assets/js/your-custom-head-script.js




# Defaults
defaults:
  # _pages and everything else
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      use_math: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
      comments: # true
      share: true
      related: true
      use_math: false



author:
  name: "Tomáš Karella"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Just another PhD. student publishing notes." # Note: Markdown is allowed
  location: "CAS, Prague, CZE"
  links:
    - label: "Personal website"
      icon: "fas fa-fw fa-link"
      url: "http://zoi.utia.cas.cz/karella"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/karellat"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tomas-karella"